services:
  postgres:
    image: postgres:15
    container_name: automechanic-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  rabbitmq:
    container_name: rabbitmq-automechanic
    image: rabbitmq:management
    env_file:
      - .env.dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
  postgres_data: