services:
  postgres:
    image: postgres:15
    container_name: automechanic-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - automechanic-postgres
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: automechanic-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      - spring.datasource.url=${DATABASE_URL}
      - spring.datasource.username=${DATABASE_USER}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - spring.profiles.active=${SPRING_PROFILES_ACTIVE}
    depends_on:
      - postgres
      - rabbitmq
    restart: always
    networks:
      - automechanic-postgres
  rabbitmq:
    container_name: rabbitmq-automechanic
    image: rabbitmq:management
    env_file:
      - .env.prod
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - automechanic-postgres

volumes:
  postgres_data:

networks:
  automechanic-postgres:
    driver: bridge